version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: telegram-server-dash
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./config:/app/config:ro
    environment:
      - TZ=Asia/Jakarta
    networks:
      - tsd-network

networks:
  tsd-network:
    driver: bridge